"""add payment link to sections

Revision ID: 10341f0680ca
Revises: c1b2f3d4e5a6
Create Date: 2026-06-05 16:11:32.194386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10341f0680ca'
down_revision: Union[str, None] = 'c1b2f3d4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spi_event_id'), table_name='section_payment_initiations')
    op.drop_index(op.f('ix_spi_section_id'), table_name='section_payment_initiations')
    op.drop_index(op.f('ix_spi_user_id'), table_name='section_payment_initiations')
    op.create_index(op.f('ix_section_payment_initiations_event_id'), 'section_payment_initiations', ['event_id'], unique=False)
    op.create_index(op.f('ix_section_payment_initiations_section_id'), 'section_payment_initiations', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_payment_initiations_user_id'), 'section_payment_initiations', ['user_id'], unique=False)
    op.add_column('sections', sa.Column('payment_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'payment_link')
    op.drop_index(op.f('ix_section_payment_initiations_user_id'), table_name='section_payment_initiations')
    op.drop_index(op.f('ix_section_payment_initiations_section_id'), table_name='section_payment_initiations')
    op.drop_index(op.f('ix_section_payment_initiations_event_id'), table_name='section_payment_initiations')
    op.create_index(op.f('ix_spi_user_id'), 'section_payment_initiations', ['user_id'], unique=False)
    op.create_index(op.f('ix_spi_section_id'), 'section_payment_initiations', ['section_id'], unique=False)
    op.create_index(op.f('ix_spi_event_id'), 'section_payment_initiations', ['event_id'], unique=False)
    # ### end Alembic commands ###
