"""add_tickets_gift_team_support_to_orders

Revision ID: 78634978582e
Revises: 10341f0680ca
Create Date: 2026-06-12 22:03:26.618519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78634978582e'
down_revision: Union[str, None] = '10341f0680ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tickets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('gift_option', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('team_support', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'team_support')
    op.drop_column('orders', 'gift_option')
    op.drop_column('orders', 'tickets')
    # ### end Alembic commands ###
